import { ModalServiceProps } from './type';
declare const _default: import('vue').DefineComponent<ModalServiceProps, {}, {}, {}, {}, import('vue').ComponentOptionsMixin, import('vue').ComponentOptionsMixin, {}, string, import('vue').PublicProps, Readonly<ModalServiceProps> & Readonly<{}>, {
    top: number;
    unmountOnClose: boolean;
    popupContainer: import('..').PopupContainer;
    renderToBody: boolean;
    width: number | string;
    content: import('../_shared/type').RenderContent;
    footer: boolean;
    title: string & import('../_shared/type').RenderContent;
    mask: boolean;
    closable: boolean;
    bodyStyle: import('vue').CSSProperties;
    titleAlign: import('./type').ModalTitleAlign;
    alignCenter: boolean;
    maskClosable: boolean;
    hideCancel: boolean;
    okText: string;
    cancelText: string;
    okLoading: boolean;
    okButtonProps: import('..').ButtonProps;
    cancelButtonProps: import('..').ButtonProps;
    maskStyle: import('vue').CSSProperties;
    modalClass: import('../_shared/type').ClassName;
    modalStyle: import('vue').CSSProperties;
    escToClose: boolean;
    draggable: boolean;
    fullscreen: boolean;
    maskAnimationName: string;
    modalAnimationName: string;
    bodyClass: import('../_shared/type').ClassName;
    hideTitle: boolean;
    simple: boolean;
    onBeforeCancel: import('./type').OnBeforeCancel;
    onBeforeOk: import('./type').OnBeforeOk;
}, {}, {}, {}, string, import('vue').ComponentProvideOptions, false, {}, any>;
export default _default;
