export declare function isElement(value: unknown): value is Element;
export declare function isNull(value: unknown): value is null;
export declare function isUndefined(value: unknown): value is undefined;
export declare function isNaN(value: unknown): value is number;
export declare function isNumber(value: unknown): value is number;
export declare function isString(value: unknown): value is string;
export declare function isBoolean(value: unknown): value is boolean;
export declare function isRegExp(value: unknown): value is RegExp;
export declare function isDate(value: unknown): value is Date;
export declare function isFunction(value: unknown): value is Function;
export declare function isArray(value: unknown): value is Array<unknown>;
export declare function isObject(value: unknown): value is Record<string, unknown>;
declare const _default: {
    element: typeof isElement;
    null: typeof isNull;
    undefined: typeof isUndefined;
    nan: typeof isNaN;
    number: typeof isNumber;
    string: typeof isString;
    boolean: typeof isBoolean;
    regexp: typeof isRegExp;
    date: typeof isDate;
    function: typeof isFunction;
    array: typeof isArray;
    object: typeof isObject;
};
export default _default;
